from pathlib import Path

from el_shaddai import cli
from el_shaddai.atlas_adapter import AtlasResult, atlas_structure_from_pillars, bndx_role_inputs_from_csv, compute_bndx_role_proxies, latest_bndx_role_inputs
from el_shaddai.config import ROLE_COMPONENT_WEIGHTS
from el_shaddai.report import write_markdown
from el_shaddai.role_score import score_role
from el_shaddai.scoring import score_all


def _base_prices(days: int = 90):
    return {
        "BNDX": [48 + i * 0.03 + ((i % 5) - 2) * 0.01 for i in range(days)],
        "TLT": [92 + i * 0.01 + ((i % 7) - 3) * 0.02 for i in range(days)],
        "BND": [72 + i * 0.02 for i in range(days)],
        "HYG": [78 + i * 0.03 for i in range(days)],
        "UUP": [28 - i * 0.002 for i in range(days)],
        "BWX": [24 + i * 0.02 for i in range(days)],
        "__dates__": [f"2026-03-{(i % 30) + 1:02d}" for i in range(days)],
    }


def test_sample_atlas_inputs_csv_generates_bndx_proxies():
    result = bndx_role_inputs_from_csv("data/sample_atlas_inputs.csv")

    assert result.used_atlas is True
    assert set(result.role_inputs["BNDX"]) == set(ROLE_COMPONENT_WEIGHTS["BNDX"])
    assert result.structural_status == "Atlas Standing"
    assert result.source == "manual A.T.L.A.S. CSV: data/sample_atlas_inputs.csv"


def test_bndx_adjacent_pillar_failure_cap_35_is_applied():
    inputs = {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["BNDX"]} | {"sovereign_trust": -2.0, "currency_order": -2.0}
    result = score_role("BNDX", {"BNDX": inputs})

    assert result.score <= 35.0
    assert any("adjacent-pillar" in cap for cap in result.applied_caps)
    assert "Atlas Cannot Hold" in result.role_interpretation


def test_bndx_diagonal_pillar_failure_cap_50_is_applied():
    inputs = {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["BNDX"]} | {"sovereign_trust": -2.0, "liquidity_flow": -2.0}
    result = score_role("BNDX", {"BNDX": inputs})

    assert result.score <= 50.0
    assert any("diagonal-pillar" in cap for cap in result.applied_caps)
    assert "Atlas Kneeling" in result.role_interpretation


def test_bndx_three_pillar_failure_cap_20_is_applied():
    inputs = {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["BNDX"]} | {
        "sovereign_trust": -2.0,
        "currency_order": -2.0,
        "liquidity_flow": -2.0,
    }
    result = score_role("BNDX", {"BNDX": inputs})

    assert result.score <= 20.0
    assert any("three-pillar" in cap for cap in result.applied_caps)
    assert "Atlas Fallen" in result.role_interpretation


def test_atlas_geometry_reports_strained_for_single_failed_pillar():
    status, interpretation, failed, caps = atlas_structure_from_pillars(
        {"sovereign_trust": 20.0, "currency_order": 50.0, "liquidity_flow": 50.0, "diversification_integrity": 50.0}
    )

    assert status == "Atlas Strained"
    assert "One pillar weakened" in interpretation
    assert failed == ["sovereign_trust"]
    assert caps == []


def test_hyg_decline_makes_liquidity_flow_negative():
    prices = _base_prices()
    prices["HYG"] = [80 - i * 0.15 for i in range(90)]

    result = compute_bndx_role_proxies(prices)

    assert result.proxies["liquidity_flow"] < 0.0
    assert result.proxies["global_credit_stress"] < 0.0


def test_cli_atlas_fallback_exits_cleanly(tmp_path: Path, monkeypatch):
    monkeypatch.setattr(
        cli,
        "latest_bndx_role_inputs",
        lambda: AtlasResult(
            {"BNDX": {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["BNDX"]}},
            {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["BNDX"]},
            {name: "neutral fallback" for name in ROLE_COMPONENT_WEIGHTS["BNDX"]},
            ["warning: atlas fallback"],
            "unknown",
            "test",
            False,
            {},
            [],
            "Atlas Standing",
            "Winter blanket remains intact.",
            [],
        ),
    )

    assert cli.main(["--use-atlas-bndx-role", "--output-dir", str(tmp_path)]) == 0
    assert (tmp_path / "el_shaddai_report.md").exists()


def test_report_includes_atlas_structural_details(tmp_path: Path):
    prices = {asset: [100 - i * 0.1 for i in range(260)] for asset in ["VT", "BNDX", "TLT", "TIP", "XLRE", "GLDM", "DBC", "BTC"]}
    atlas = bndx_role_inputs_from_csv("data/sample_atlas_inputs.csv")
    scores = score_all(prices, atlas.role_inputs, "2026-03-31")
    report_path = write_markdown(scores, tmp_path, "test", atlas_result=atlas)
    text = report_path.read_text(encoding="utf-8")

    assert "## BNDX Role inputs generated by A.T.L.A.S." in text
    assert "Structural status: Atlas Standing" in text
    assert "The Four Pillars of Atlas" in text
    assert "Proxy table:" in text


def test_latest_bndx_role_inputs_falls_back_on_fetch_failure(monkeypatch):
    monkeypatch.setattr("el_shaddai.atlas_adapter.fetch_atlas_price_data", lambda *_args, **_kwargs: (_ for _ in ()).throw(OSError("no data")))

    result = latest_bndx_role_inputs()

    assert result.used_atlas is False
    assert all(value == 0.0 for value in result.role_inputs["BNDX"].values())
    assert any("neutral BNDX Role proxy fallback" in warning for warning in result.warnings)
