from pathlib import Path

from el_shaddai import cli
from el_shaddai.config import ROLE_COMPONENT_WEIGHTS
from el_shaddai.inferno_adapter import InfernoResult, compute_tip_role_proxies, latest_tip_role_inputs, tip_role_inputs_from_csv
from el_shaddai.report import write_markdown
from el_shaddai.role_score import score_role
from el_shaddai.scoring import score_all


def _inflation_gap_rows():
    return [
        {"date": "2025-01-01", "CPI_YOY": 2.0, "CORE_CPI_YOY": 2.0, "PCE_YOY": 2.0, "CORE_PCE_YOY": 2.0, "T5YIE": 2.0, "T10YIE": 2.0, "DFII10": 0.5, "UNRATE": 4.0, "DTWEXBGS": 100.0, "TIP": 100.0, "TLT": 100.0, "DBC": 25.0},
        {"date": "2026-01-01", "CPI_YOY": 5.0, "CORE_CPI_YOY": 4.5, "PCE_YOY": 4.0, "CORE_PCE_YOY": 3.8, "T5YIE": 2.1, "T10YIE": 2.0, "DFII10": 0.8, "UNRATE": 4.8, "DTWEXBGS": 101.0, "TIP": 106.0, "TLT": 100.0, "DBC": 28.0},
    ]


def test_inflation_high_breakeven_low_raises_expectation_gap():
    result = compute_tip_role_proxies(_inflation_gap_rows())

    assert result.used_inferno is True
    assert result.proxies["inflation_expectation_gap"] > 1.0
    assert "underpricing" in result.inflation_regime_interpretation


def test_tip_real_rate_shock_cap_is_applied():
    result = score_role(
        "TIP",
        {"TIP": {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["TIP"]} | {"real_rate_shock": -2.0}},
    )

    assert result.score <= 55.0
    assert any("real-rate shock cap" in cap for cap in result.applied_caps)


def test_tip_deflation_pressure_lowers_role_score():
    result = score_role(
        "TIP",
        {"TIP": {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["TIP"]} | {"deflation_pressure": -2.0}},
    )

    assert result.penalty_score < 50.0
    assert result.score < 50.0


def test_tip_macro_submission_lowers_role_score():
    result = score_role(
        "TIP",
        {"TIP": {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["TIP"]} | {"macro_submission": -2.0}},
    )

    assert result.penalty_score < 50.0
    assert result.score < 50.0


def test_inferno_metrics_are_reported(tmp_path: Path):
    prices = {asset: [100 - i * 0.1 for i in range(260)] for asset in ["VT", "BNDX", "TLT", "TIP", "XLRE", "GLDM", "DBC", "BTC"]}
    scores = score_all(prices, {"TIP": {"real_rate_shock": -2.0}}, "2026-01-01")
    report = write_markdown(scores, tmp_path, "test", inferno_result=compute_tip_role_proxies(_inflation_gap_rows()))
    text = report.read_text(encoding="utf-8")

    assert "## TIP Role inputs generated by I.N.F.E.R.N.O." in text
    assert "raw_weighted_score" in text
    assert "penalty_adjusted_score" in text


def test_cli_inferno_fallback_exits_cleanly(tmp_path: Path, monkeypatch):
    monkeypatch.setattr(
        cli,
        "latest_tip_role_inputs",
        lambda: InfernoResult(
            {"TIP": {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["TIP"]}},
            {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["TIP"]},
            {},
            ["warning: inferno fallback"],
            "unknown",
            "test",
            False,
            "neutral fallback",
            [],
        ),
    )

    assert cli.main(["--use-inferno-tip-role", "--output-dir", str(tmp_path)]) == 0
    assert (tmp_path / "el_shaddai_report.md").exists()


def test_latest_tip_role_inputs_falls_back_on_fetch_failure(monkeypatch):
    monkeypatch.setattr("el_shaddai.inferno_adapter.fetch_inferno_fred_data", lambda *_args, **_kwargs: (_ for _ in ()).throw(OSError("FRED 403")))

    result = latest_tip_role_inputs()

    assert result.used_inferno is False
    assert all(value == 0.0 for value in result.role_inputs["TIP"].values())


def test_manual_inferno_csv_route_uses_data():
    result = tip_role_inputs_from_csv("data/sample_inferno_inputs.csv")

    assert result.used_inferno is True
    assert result.source == "manual I.N.F.E.R.N.O. CSV: data/sample_inferno_inputs.csv"
    assert result.proxies["real_rate_shock"] < 0.0
    assert result.proxies["deflation_pressure"] < 0.0


def test_manual_inferno_csv_inflation_gap_positive_for_underpricing(tmp_path: Path):
    csv_path = tmp_path / "inferno_underpricing.csv"
    csv_path.write_text(
        "date,cpi,core_cpi,pce,core_pce,breakeven_5y,breakeven_10y,dfii10,unrate,broad_dollar,tip_close,tlt_close,dbc_close\n"
        "2025-01-01,2.0,2.0,2.0,2.0,2.0,2.0,0.5,4.0,100,100,100,25\n"
        "2026-01-01,5.0,4.5,4.0,3.8,2.1,2.0,0.8,4.8,101,106,100,28\n",
        encoding="utf-8",
    )

    result = tip_role_inputs_from_csv(str(csv_path))

    assert result.used_inferno is True
    assert result.proxies["inflation_expectation_gap"] > 1.0


def test_manual_inferno_csv_real_rate_shock_triggers_tip_cap():
    result = tip_role_inputs_from_csv("data/sample_inferno_inputs.csv")
    role = score_role("TIP", result.role_inputs)

    assert any("real-rate shock cap" in cap for cap in role.applied_caps)
    assert role.score <= 55.0


def test_cli_inferno_inputs_csv_changes_tip_role_score(tmp_path: Path):
    assert cli.main(["--inferno-inputs-csv", "data/sample_inferno_inputs.csv", "--output-dir", str(tmp_path)]) == 0
    report = (tmp_path / "el_shaddai_report.md").read_text(encoding="utf-8")
    scores = (tmp_path / "el_shaddai_scores.csv").read_text(encoding="utf-8")
    tip_line = next(line for line in scores.splitlines() if line.startswith("TIP,"))

    assert "Source: manual I.N.F.E.R.N.O. CSV: data/sample_inferno_inputs.csv" in report
    assert "Used I.N.F.E.R.N.O. data: True" in report
    assert ",50.00," not in tip_line
