from pathlib import Path

from el_shaddai import cli
from el_shaddai.config import ROLE_COMPONENT_WEIGHTS
from el_shaddai.lode_adapter import LodeResult, compute_tlt_role_proxies, latest_tlt_role_inputs


def _sample_lode_rows():
    return [
        {
            "date": "2020-01-01",
            "T10Y2Y": 1.0,
            "DFII10": -0.5,
            "GFDEGDQ188S": 90.0,
            "A091RC1Q027SBEA": 400.0,
            "W006RC1Q027SBEA": 4000.0,
            "FDHBFIN": 7000.0,
            "GFDEBTN": 23000000.0,
        },
        {
            "date": "2026-01-01",
            "T10Y2Y": -1.2,
            "DFII10": 2.0,
            "GFDEGDQ188S": 125.0,
            "A091RC1Q027SBEA": 950.0,
            "W006RC1Q027SBEA": 4300.0,
            "FDHBFIN": 8500.0,
            "GFDEBTN": 35000000.0,
        },
    ]


def test_latest_tlt_role_inputs_falls_back_to_neutral_without_fred(monkeypatch):
    def fail_fetch(*_args, **_kwargs):
        raise OSError("FRED unavailable")

    monkeypatch.setattr("el_shaddai.lode_adapter.fetch_lode_fred_data", fail_fetch)

    result = latest_tlt_role_inputs()

    assert result.used_lode is False
    assert all(value == 0.0 for value in result.role_inputs["TLT"].values())
    assert any("neutral TLT Role proxy fallback" in warning for warning in result.warnings)


def test_compute_tlt_role_proxies_from_manual_lode_data():
    result = compute_tlt_role_proxies(_sample_lode_rows())

    assert result.used_lode is True
    assert set(result.role_inputs["TLT"]) == set(ROLE_COMPONENT_WEIGHTS["TLT"])
    assert result.role_inputs["TLT"]["yield_curve"] > 0
    assert result.role_inputs["TLT"]["debt_sustainability"] < 0
    assert "10Y-2Y spread" in result.reasons["yield_curve"]


def test_cli_lode_option_can_change_tlt_role_score(tmp_path: Path, monkeypatch):
    lode_result = LodeResult(
        role_inputs={"TLT": {name: 1.0 for name in ROLE_COMPONENT_WEIGHTS["TLT"]}},
        proxies={name: 1.0 for name in ROLE_COMPONENT_WEIGHTS["TLT"]},
        reasons={name: "test reason" for name in ROLE_COMPONENT_WEIGHTS["TLT"]},
        warnings=[],
        data_date="2026-01-01",
        source="test L.O.D.E.",
        used_lode=True,
    )
    monkeypatch.setattr(cli, "latest_tlt_role_inputs", lambda: lode_result)

    plain_dir = tmp_path / "plain"
    lode_dir = tmp_path / "lode"
    assert cli.main(["--output-dir", str(plain_dir)]) == 0
    assert cli.main(["--use-lode-tlt-role", "--output-dir", str(lode_dir)]) == 0

    plain_csv = (plain_dir / "el_shaddai_scores.csv").read_text(encoding="utf-8")
    lode_csv = (lode_dir / "el_shaddai_scores.csv").read_text(encoding="utf-8")

    assert "TLT,62.43,50.00,50.00" in plain_csv
    assert "TLT,62.43,75.00,62.43" in lode_csv
    assert "TLT Role inputs generated by L.O.D.E." in (lode_dir / "el_shaddai_report.md").read_text(encoding="utf-8")
