from dataclasses import replace
from pathlib import Path

from el_shaddai import cli
from el_shaddai.arcadia_adapter import (
    ArcadiaResult,
    compute_xlre_role_proxies,
    latest_xlre_role_inputs,
    xlre_role_inputs_from_csv,
)
from el_shaddai.config import ROLE_COMPONENT_WEIGHTS
from el_shaddai.report import write_markdown
from el_shaddai.role_score import score_role
from el_shaddai.scoring import score_all


def _base_prices(days: int = 90):
    return {
        "XLRE": [40 + i * 0.08 + ((i % 5) - 2) * 0.02 for i in range(days)],
        "SPY": [500 + i * 0.5 + ((i % 7) - 3) * 0.05 for i in range(days)],
        "VNQ": [85 + i * 0.12 + ((i % 4) - 1.5) * 0.03 for i in range(days)],
        "HYG": [78 + i * 0.03 for i in range(days)],
        "UUP": [28 - i * 0.01 for i in range(days)],
        "DBC": [24 + i * 0.03 for i in range(days)],
        "TLT": [92 + i * 0.02 for i in range(days)],
        "^TNX": [4.0 + i * 0.001 for i in range(days)],
        "__dates__": [f"2026-03-{(i % 30) + 1:02d}" for i in range(days)],
    }


def test_sample_arcadia_prices_csv_generates_xlre_proxies():
    result = xlre_role_inputs_from_csv("data/sample_arcadia_prices.csv")

    assert result.used_arcadia is True
    assert set(result.role_inputs["XLRE"]) == set(ROLE_COMPONENT_WEIGHTS["XLRE"])
    assert all(-2.0 <= value <= 2.0 for value in result.proxies.values())
    assert result.source == "manual A.R.C.A.D.I.A. CSV: data/sample_arcadia_prices.csv"


def test_xlre_real_rate_shock_cap_55_is_applied():
    result = score_role("XLRE", {"XLRE": {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["XLRE"]} | {"real_rate_shock": -2.0}})

    assert result.score <= 55.0
    assert any("real-rate shock cap" in cap for cap in result.applied_caps)


def test_xlre_real_rate_and_credit_cap_45_is_applied():
    result = score_role(
        "XLRE",
        {"XLRE": {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["XLRE"]} | {"real_rate_shock": -2.0, "credit_stress": -2.0}},
    )

    assert result.score <= 45.0
    assert any("rates + credit cap" in cap for cap in result.applied_caps)


def test_xlre_real_rate_credit_and_equity_cap_35_is_applied():
    result = score_role(
        "XLRE",
        {
            "XLRE": {name: 2.0 for name in ROLE_COMPONENT_WEIGHTS["XLRE"]}
            | {"real_rate_shock": -2.0, "credit_stress": -2.0, "equity_submission": -2.0}
        },
    )

    assert result.score <= 35.0
    assert any("full role-failure cap" in cap for cap in result.applied_caps)


def test_hyg_decline_makes_credit_stress_negative():
    prices = _base_prices()
    prices["HYG"] = [80 - i * 0.15 for i in range(90)]

    result = compute_xlre_role_proxies(prices)

    assert result.proxies["credit_stress"] < 0.0


def test_uup_rise_makes_dollar_headwind_negative():
    prices = _base_prices()
    prices["UUP"] = [28 + i * 0.05 for i in range(90)]

    result = compute_xlre_role_proxies(prices)

    assert result.proxies["dollar_headwind"] < 0.0


def test_extreme_xlre_spy_correlation_makes_equity_submission_negative():
    prices = _base_prices()
    prices["SPY"] = [value * 12.5 for value in prices["XLRE"]]

    result = compute_xlre_role_proxies(prices)

    assert result.proxies["equity_submission"] < 0.0


def test_manual_csv_route_reports_used_arcadia_data_true(tmp_path: Path):
    assert cli.main(["--arcadia-prices-csv", "data/sample_arcadia_prices.csv", "--output-dir", str(tmp_path)]) == 0
    report = (tmp_path / "el_shaddai_report.md").read_text(encoding="utf-8")

    assert "Used A.R.C.A.D.I.A. data: True" in report


def test_cli_arcadia_fallback_exits_cleanly(tmp_path: Path, monkeypatch):
    monkeypatch.setattr(
        cli,
        "latest_xlre_role_inputs",
        lambda: ArcadiaResult(
            {"XLRE": {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["XLRE"]}},
            {name: 0.0 for name in ROLE_COMPONENT_WEIGHTS["XLRE"]},
            {name: "neutral fallback" for name in ROLE_COMPONENT_WEIGHTS["XLRE"]},
            ["warning: arcadia fallback"],
            "unknown",
            "test",
            False,
            {},
            [],
            "neutral fallback",
        ),
    )

    assert cli.main(["--use-arcadia-xlre-role", "--output-dir", str(tmp_path)]) == 0
    assert (tmp_path / "el_shaddai_report.md").exists()


def test_report_includes_arcadia_raw_adjusted_groups_caps_and_interpretation(tmp_path: Path):
    prices = {asset: [100 - i * 0.1 for i in range(260)] for asset in ["VT", "BNDX", "TLT", "TIP", "XLRE", "GLDM", "DBC", "BTC"]}
    arcadia = xlre_role_inputs_from_csv("data/sample_arcadia_prices.csv")
    scores = score_all(prices, arcadia.role_inputs, "2026-03-31")
    report_path = write_markdown(scores, tmp_path, "test", arcadia_result=arcadia)
    text = report_path.read_text(encoding="utf-8")

    assert "## XLRE Role inputs generated by A.R.C.A.D.I.A." in text
    assert "Raw metrics:" in text
    assert "Role raw_weighted_score" in text
    assert "Role penalty_adjusted_score" in text
    assert "Role core_score" in text
    assert "Role support_score" in text
    assert "Role penalty_score" in text
    assert "Role applied_caps" in text
    assert "Real-estate regime interpretation:" in text
    assert "Proxy table:" in text


def test_latest_xlre_role_inputs_falls_back_on_fetch_failure(monkeypatch):
    monkeypatch.setattr("el_shaddai.arcadia_adapter.fetch_arcadia_price_data", lambda *_args, **_kwargs: (_ for _ in ()).throw(OSError("no data")))

    result = latest_xlre_role_inputs()

    assert result.used_arcadia is False
    assert all(value == 0.0 for value in result.role_inputs["XLRE"].values())


def test_arcadia_raw_metrics_expose_shared_inputs_for_double_counting_review():
    result = compute_xlre_role_proxies(_base_prices())

    assert "xlre_spy_relative_return" in result.raw_metrics
    assert "vnq_spy_relative_return" in result.raw_metrics
    assert "hyg_spy_divergence" in result.raw_metrics


def test_arcadia_score_breakdown_identifies_role_driver_and_proxy_contributions(tmp_path: Path):
    prices = _base_prices()
    prices["XLRE"] = [40 + ((i % 2) * 0.01) for i in range(90)]
    prices["SPY"] = [value * 12.5 for value in prices["XLRE"]]
    prices["HYG"] = [80 - i * 0.20 for i in range(90)]
    prices["UUP"] = [28 + i * 0.06 for i in range(90)]
    prices["TLT"] = [100 - i * 0.20 for i in range(90)]
    prices["^TNX"] = [3.5 + i * 0.02 for i in range(90)]
    arcadia = compute_xlre_role_proxies(prices)
    diagnostic_proxies = {name: -2.0 for name in ROLE_COMPONENT_WEIGHTS["XLRE"]}
    arcadia = replace(arcadia, role_inputs={"XLRE": diagnostic_proxies}, proxies=diagnostic_proxies)
    scores = score_all({"XLRE": prices["XLRE"]}, arcadia.role_inputs, "2026-06-11")

    report = write_markdown(scores, tmp_path, "test", arcadia_result=arcadia).read_text(encoding="utf-8")

    assert "### A.R.C.A.D.I.A. score breakdown" in report
    assert "final_score driver: role_score（役割proxy要因がfinal_scoreを規定）" in report
    assert "| observed proxy | raw value | normalized score | contribution | direction | reason / interpretation |" in report
    for proxy in ("REIT Relative Strength proxy", "金利環境 proxy", "HYG proxy", "UUP proxy", "DBC proxy", "XLRE/SPY proxy"):
        assert proxy in report
    assert "Role component contribution reconciliation:" in report
    assert "| rental_cashflow |" in report
    assert "REIT Relative Strength vs XLRE/SPY: 同一指標そのものではない" in report
    assert "共通ショック時の重複ペナルティ疑義あり" in report
    assert "スコア計算ロジック自体は変更していない" in report
