from pathlib import Path

from el_shaddai import cli
from el_shaddai.aura_adapter import (
    AuraResult,
    compute_gldm_role_proxies,
    compute_gold_correlations,
    compute_gold_regime,
    latest_gldm_role_inputs,
)
from el_shaddai.config import ROLE_COMPONENT_WEIGHTS


def _sample_aura_prices():
    days = 90
    gld = [100 + i * 0.5 for i in range(days)]
    return {
        "GLD": gld,
        "SPY": [120 - i * 0.2 for i in range(days)],
        "TLT": [90 + i * 0.1 for i in range(days)],
        "DBC": [20 + i * 0.45 for i in range(days)],
        "UUP": [30 - i * 0.3 for i in range(days)],
        "BTC-USD": [50000 + i * 250 for i in range(days)],
    }


def test_compute_gold_correlations_and_regime():
    correlations = compute_gold_correlations(_sample_aura_prices(), window=60)
    regime = compute_gold_regime(correlations)

    assert set(correlations) == {"SPY", "TLT", "DBC", "UUP", "BTC-USD"}
    assert regime["dominant_anchor"] in correlations
    assert isinstance(regime["gri_score"], float)


def test_compute_gldm_role_proxies_are_bounded_and_explainable():
    result = compute_gldm_role_proxies(_sample_aura_prices(), window=60)

    assert result.used_aura is True
    assert set(result.role_inputs["GLDM"]) == set(ROLE_COMPONENT_WEIGHTS["GLDM"])
    assert all(-2.0 <= value <= 2.0 for value in result.role_inputs["GLDM"].values())
    assert result.dominant_anchor in {"SPY", "TLT", "DBC", "UUP", "BTC-USD"}
    assert "GRI" in result.reasons["dominant_anchor_strength"]


def test_latest_gldm_role_inputs_falls_back_to_neutral_without_yfinance(monkeypatch):
    def fail_fetch(*_args, **_kwargs):
        raise OSError("yfinance unavailable")

    monkeypatch.setattr("el_shaddai.aura_adapter.fetch_aura_price_data", fail_fetch)

    result = latest_gldm_role_inputs()

    assert result.used_aura is False
    assert all(value == 0.0 for value in result.role_inputs["GLDM"].values())
    assert any("neutral GLDM Role proxy fallback" in warning for warning in result.warnings)


def test_cli_aura_option_can_change_gldm_role_score(tmp_path: Path, monkeypatch):
    aura_result = AuraResult(
        role_inputs={"GLDM": {name: 1.0 for name in ROLE_COMPONENT_WEIGHTS["GLDM"]}},
        proxies={name: 1.0 for name in ROLE_COMPONENT_WEIGHTS["GLDM"]},
        reasons={name: "test reason" for name in ROLE_COMPONENT_WEIGHTS["GLDM"]},
        warnings=[],
        data_date="2026-01-01",
        source="test A.U.R.A.",
        used_aura=True,
        correlations={"DBC": 0.5, "TLT": -0.1, "UUP": -0.4, "BTC-USD": 0.3, "SPY": -0.2},
        dominant_anchor="DBC",
        dominant_correlation=0.5,
        gri_score=1.3,
        gri_interpretation="liquidity/inflation regime",
    )
    monkeypatch.setattr(cli, "latest_gldm_role_inputs", lambda: aura_result)

    plain_dir = tmp_path / "plain"
    aura_dir = tmp_path / "aura"
    assert cli.main(["--output-dir", str(plain_dir)]) == 0
    assert cli.main(["--use-aura-gldm-role", "--output-dir", str(aura_dir)]) == 0

    plain_csv = (plain_dir / "el_shaddai_scores.csv").read_text(encoding="utf-8")
    aura_csv = (aura_dir / "el_shaddai_scores.csv").read_text(encoding="utf-8")

    assert "GLDM,46.03,50.00,46.03" in plain_csv
    assert "GLDM,46.03,75.00,46.03" in aura_csv
    assert "GLDM Role inputs generated by A.U.R.A." in (aura_dir / "el_shaddai_report.md").read_text(encoding="utf-8")
    assert "GLDM Role generated by A.U.R.A." in (aura_dir / "el_shaddai_dashboard.html").read_text(encoding="utf-8")
