"""Configuration for El Shaddai v1.5.1.

The defaults intentionally favor transparency over sophistication.  Every score
is derived from bounded, inspectable components and can be audited from the
Markdown report generated by the CLI.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Mapping, Optional

ASSETS: List[str] = ["VT", "BNDX", "TLT", "TIP", "XLRE", "GLDM", "DBC", "BTC"]
ROLE_ASSETS: List[str] = ["BNDX", "TLT", "TIP", "XLRE", "GLDM", "DBC"]
PERMANENT_ASSETS: List[str] = ["VT", "BTC"]

PRICE_COMPONENT_WEIGHTS: Mapping[str, float] = {
    "rsi": 0.20,
    "dma_200_deviation": 0.20,
    "range_52w_position": 0.20,
    "z_score": 0.15,
    "weekly_drawdown": 0.10,
    "range_5y_position": 0.15,
}

ROLE_COMPONENT_WEIGHTS: Mapping[str, Mapping[str, float]] = {
    "BNDX": {"dxy": 0.25, "us_10y_yield": 0.25, "global_bond_trend": 0.30, "fx_environment": 0.20},
    "TLT": {"recession_pressure": 0.20, "us_10y_yield": 0.10, "us_30y_yield": 0.10, "yield_curve": 0.15, "real_rate": 0.15, "debt_sustainability": 0.10, "interest_burden": 0.10, "foreign_demand": 0.10},
    "TIP": {"inflation_threat": 0.18, "inflation_expectation_gap": 0.18, "purchasing_power_protection": 0.18, "stagflation_pressure": 0.11, "inflation_regime_strength": 0.11, "real_rate_shock": 0.08, "deflation_pressure": 0.08, "macro_submission": 0.08},
    "GLDM": {"safe_haven_pressure": 0.15, "real_rate": 0.10, "dxy": 0.10, "central_bank_buying": 0.10, "geopolitical_risk": 0.10, "inflation_regime": 0.10, "currency_hedge": 0.10, "liquidity_regime": 0.10, "macro_independence": 0.10, "dominant_anchor_strength": 0.05},
    "XLRE": {"reit_trend": 0.40, "interest_rate_pressure": 0.35, "sector_relative_strength": 0.25},
    "DBC": {"crb": 0.20, "gsci": 0.20, "bcom": 0.20, "oil": 0.15, "metals": 0.15, "agriculture": 0.10},
}


ROLE_COMPONENT_GROUPS: Mapping[str, Mapping[str, str]] = {
    "BNDX": {"dxy": "core", "us_10y_yield": "core", "global_bond_trend": "core", "fx_environment": "core"},
    "TLT": {
        "recession_pressure": "core",
        "yield_curve": "core",
        "real_rate": "core",
        "us_10y_yield": "support",
        "us_30y_yield": "support",
        "debt_sustainability": "risk_penalty",
        "interest_burden": "risk_penalty",
        "foreign_demand": "risk_penalty",
    },
    "TIP": {"inflation_threat": "core", "inflation_expectation_gap": "core", "purchasing_power_protection": "core", "stagflation_pressure": "support", "inflation_regime_strength": "support", "real_rate_shock": "risk_penalty", "deflation_pressure": "risk_penalty", "macro_submission": "risk_penalty"},
    "GLDM": {
        "macro_independence": "core",
        "currency_hedge": "core",
        "safe_haven_pressure": "core",
        "inflation_regime": "core",
        "liquidity_regime": "support",
        "dominant_anchor_strength": "support",
        "central_bank_buying": "context",
        "geopolitical_risk": "context",
        "real_rate": "context",
        "dxy": "context",
    },
    "XLRE": {"reit_trend": "core", "interest_rate_pressure": "core", "sector_relative_strength": "core"},
    "DBC": {"crb": "core", "gsci": "core", "bcom": "core", "oil": "core", "metals": "core", "agriculture": "core"},
}

ROLE_GROUP_WEIGHTS: Mapping[str, Mapping[str, float]] = {
    "TLT": {"core": 0.60, "support": 0.25, "risk_penalty": 0.15},
    "GLDM": {"core": 0.75, "support": 0.20, "context": 0.05},
    "TIP": {"core": 0.60, "support": 0.20, "risk_penalty": 0.20},
}

# Neutral proxy values keep the system running when no macro data is supplied.
# All values are deliberately simple: positive numbers mean the role backdrop is
# helpful, negative numbers mean impaired, and zero is neutral.
DEFAULT_ROLE_INPUTS: Mapping[str, Mapping[str, float]] = {
    "BNDX": {"dxy": 0.0, "us_10y_yield": 0.0, "global_bond_trend": 0.0, "fx_environment": 0.0},
    "TLT": {"recession_pressure": 0.0, "us_10y_yield": 0.0, "us_30y_yield": 0.0, "yield_curve": 0.0, "real_rate": 0.0, "debt_sustainability": 0.0, "interest_burden": 0.0, "foreign_demand": 0.0},
    "TIP": {"inflation_threat": 0.0, "inflation_expectation_gap": 0.0, "purchasing_power_protection": 0.0, "stagflation_pressure": 0.0, "inflation_regime_strength": 0.0, "real_rate_shock": 0.0, "deflation_pressure": 0.0, "macro_submission": 0.0},
    "GLDM": {"safe_haven_pressure": 0.0, "real_rate": 0.0, "dxy": 0.0, "central_bank_buying": 0.0, "geopolitical_risk": 0.0, "inflation_regime": 0.0, "currency_hedge": 0.0, "liquidity_regime": 0.0, "macro_independence": 0.0, "dominant_anchor_strength": 0.0},
    "XLRE": {"reit_trend": 0.0, "interest_rate_pressure": 0.0, "sector_relative_strength": 0.0},
    "DBC": {"crb": 0.0, "gsci": 0.0, "bcom": 0.0, "oil": 0.0, "metals": 0.0, "agriculture": 0.0},
}

@dataclass(frozen=True)
class DataSourceConfig:
    """Input configuration for a CLI run."""

    prices_csv: Optional[str] = None
    role_inputs_json: Optional[str] = None
    sample_days: int = 320
