"""CSV and Markdown report writers."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable, List, Optional

from .arcadia_adapter import ArcadiaResult
from .atlas_adapter import AtlasResult
from .aura_adapter import AuraResult
from .gaia_adapter import GaiaResult
from .inferno_adapter import InfernoResult
from .lode_adapter import LodeResult
from .oracle_adapter import OracleResult
from .config import ROLE_COMPONENT_GROUPS, ROLE_COMPONENT_WEIGHTS
from .scoring import AssetScore, ranking
from .text_sanitizer import sanitize_output_text

OUTPUT_FIELDS = ["asset", "price_score", "role_score", "el_shaddai_score", "label", "main_reason", "data_date", "opportunity_score", "oracle_signal", "oracle_reason"]


def role_display(score: float | None) -> str:
    return "N/A" if score is None else f"{score:.2f}"


def write_csv(scores: Iterable[AssetScore], output_dir: Path) -> Path:
    path = output_dir / "el_shaddai_scores.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS, lineterminator="\n")
        writer.writeheader()
        for score in scores:
            writer.writerow({
                "asset": score.asset,
                "price_score": f"{score.price_score:.2f}",
                "role_score": role_display(score.role_score),
                "el_shaddai_score": f"{score.el_shaddai_score:.2f}",
                "label": score.label,
                "main_reason": score.main_reason,
                "data_date": score.data_date,
                "opportunity_score": "" if score.oracle_details is None else f"{score.oracle_details.opportunity_score:.2f}",
                "oracle_signal": "" if score.oracle_details is None else score.oracle_details.oracle_signal,
                "oracle_reason": "" if score.oracle_details is None else score.oracle_details.oracle_reason,
            })
    return path


def write_markdown(
    scores: List[AssetScore],
    output_dir: Path,
    source_summary: str,
    atlas_result: Optional[AtlasResult] = None,
    lode_result: Optional[LodeResult] = None,
    inferno_result: Optional[InfernoResult] = None,
    aura_result: Optional[AuraResult] = None,
    gaia_result: Optional[GaiaResult] = None,
    arcadia_result: Optional[ArcadiaResult] = None,
    oracle_result: Optional[OracleResult] = None,
) -> Path:
    path = output_dir / "el_shaddai_report.md"
    lines = [
        "# El Shaddai Health Diagnostic Report",
        "",
        f"Data sources: {source_summary}",
        "",
        "## Asset Scores",
        "",
        "| asset | price_score | role_score | el_shaddai_score | status | label | main_reason | data_date |",
        "| --- | ---: | ---: | ---: | --- | --- | --- | --- |",
    ]
    fred_results = {"TLT": lode_result, "TIP": inferno_result}
    degraded_assets = [asset for asset, result in fred_results.items() if result is not None and result.degraded]
    failed_adapters = [
        asset for asset, result in fred_results.items()
        if result is not None and result.degraded
        and not getattr(result, "used_lode", getattr(result, "used_inferno", True))
    ]
    lines.insert(4, f"Failed adapters: {', '.join(failed_adapters) if failed_adapters else 'none'}")
    lines.insert(4, f"Degraded assets: {', '.join(degraded_assets) if degraded_assets else 'none'}")
    for score in scores:
        adapter = fred_results.get(score.asset)
        failed = score.asset in failed_adapters
        status = "degraded-neutral" if failed else ("degraded-cache" if adapter is not None and adapter.degraded else "normal")
        lines.append(
            f"| {score.asset} | {score.price_score:.2f} | {role_display(score.role_score)} | "
            f"{score.el_shaddai_score:.2f} | {status} | {score.label} | {score.main_reason} | {score.data_date} |"
        )

    lines.extend(["", "## Role Component Weights", "", "| asset | component | weight | group |", "| --- | --- | ---: | --- |"])
    for asset, weights in ROLE_COMPONENT_WEIGHTS.items():
        groups = ROLE_COMPONENT_GROUPS.get(asset, {})
        for component, weight in weights.items():
            lines.append(f"| {asset} | {component} | {weight:.2f} | {groups.get(component, 'core')} |")
    lines.extend(["", "## Genki-dama Candidate Ranking", "", "| rank | asset | score | label |", "| ---: | --- | ---: | --- |"])
    for index, score in enumerate(ranking(scores), start=1):
        lines.append(f"| {index} | {score.asset} | {score.el_shaddai_score:.2f} | {score.label} |")

    if atlas_result is not None:
        lines.extend(["", "## BNDX Role inputs generated by A.T.L.A.S.", ""])
        lines.append(f"Source: {atlas_result.source}")
        lines.append(f"Data date: {atlas_result.data_date}")
        lines.append(f"Used A.T.L.A.S. data: {atlas_result.used_atlas}")
        lines.append(f"Structural status: {atlas_result.structural_status}")
        lines.append(f"Winter Shield interpretation: {atlas_result.winter_shield_interpretation}")
        lines.append(f"Failed pillars: {', '.join(atlas_result.failed_pillars) if atlas_result.failed_pillars else 'none'}")
        bndx_score = next((score for score in scores if score.asset == "BNDX"), None)
        atlas_caps = list(atlas_result.applied_caps)
        if bndx_score is not None and bndx_score.role_details.applied_caps:
            atlas_caps.extend(cap for cap in bndx_score.role_details.applied_caps if cap not in atlas_caps)
        if atlas_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in atlas_result.warnings)
        if atlas_caps:
            lines.extend(["", "Applied caps:"])
            lines.extend(f"- {cap}" for cap in atlas_caps)
        if atlas_result.raw_metrics:
            lines.extend(["", "Raw metrics:"])
            lines.extend(f"- {name}: {value:+.6f}" for name, value in atlas_result.raw_metrics.items())
        lines.extend(["", "The Four Pillars of Atlas:", "", "| pillar | score | failed |", "| --- | ---: | --- |"])
        for name in ("sovereign_trust", "currency_order", "liquidity_flow", "diversification_integrity"):
            proxy = atlas_result.proxies.get(name, 0.0)
            pillar_score = 50.0 + proxy * 25.0
            lines.append(f"| {name} | {pillar_score:.2f} | {name in atlas_result.failed_pillars} |")
        lines.extend(["", "Proxy table:", "", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in atlas_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {atlas_result.reasons.get(name, 'neutral fallback')} |")
        lines.extend(["", "Reasons:"])
        lines.extend(f"- {name}: {reason}" for name, reason in atlas_result.reasons.items())

    if lode_result is not None:
        lines.extend(["", "## TLT Role inputs generated by L.O.D.E.", ""])
        lines.append(f"Source: {lode_result.source}")
        lines.append(f"Data date: {lode_result.data_date}")
        lines.append(f"Used L.O.D.E. data: {lode_result.used_lode}")
        lines.append(f"Degraded: {lode_result.degraded}")
        lines.append(f"Stale days: {lode_result.stale_days if lode_result.stale_days is not None else 'N/A'}")
        lines.append(f"Failed adapter: {lode_result.degraded and not lode_result.used_lode}")
        if lode_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in lode_result.warnings)
        lines.extend(["", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in lode_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {lode_result.reasons.get(name, 'neutral fallback')} |")

    if inferno_result is not None:
        lines.extend(["", "## TIP Role inputs generated by I.N.F.E.R.N.O.", ""])
        lines.append(f"Source: {inferno_result.source}")
        lines.append(f"Data date: {inferno_result.data_date}")
        lines.append(f"Used I.N.F.E.R.N.O. data: {inferno_result.used_inferno}")
        lines.append(f"Degraded: {inferno_result.degraded}")
        lines.append(f"Stale days: {inferno_result.stale_days if inferno_result.stale_days is not None else 'N/A'}")
        lines.append(f"Failed adapter: {inferno_result.degraded and not inferno_result.used_inferno}")
        lines.append(f"Inflation regime interpretation: {inferno_result.inflation_regime_interpretation}")
        tip_score = next((score for score in scores if score.asset == "TIP"), None)
        inferno_caps = list(inferno_result.applied_caps)
        if tip_score is not None and tip_score.role_details.applied_caps:
            inferno_caps.extend(cap for cap in tip_score.role_details.applied_caps if cap not in inferno_caps)
        if inferno_caps:
            lines.extend(["", "Applied caps:"])
            lines.extend(f"- {cap}" for cap in inferno_caps)
        if inferno_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in inferno_result.warnings)
        lines.extend(["", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in inferno_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {inferno_result.reasons.get(name, 'neutral fallback')} |")

    if aura_result is not None:
        lines.extend(["", "## GLDM Role inputs generated by A.U.R.A.", ""])
        lines.append(f"Source: {aura_result.source}")
        lines.append(f"Enabled: {aura_result.used_aura}")
        lines.append(f"Data date: {aura_result.data_date}")
        lines.append(f"Dominant Anchor: {aura_result.dominant_anchor}")
        lines.append(f"Dominant Correlation: {aura_result.dominant_correlation:+.3f}")
        lines.append(f"GRI score: {aura_result.gri_score:+.3f}")
        lines.append(f"GRI interpretation: {aura_result.gri_interpretation}")
        if aura_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in aura_result.warnings)
        if aura_result.correlations:
            lines.extend(["", "Correlations:"])
            lines.extend(f"- {ticker}: {value:+.3f}" for ticker, value in aura_result.correlations.items())
        lines.extend(["", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in aura_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {aura_result.reasons.get(name, 'neutral fallback')} |")

    if gaia_result is not None:
        lines.extend(["", "## DBC Role inputs generated by G.A.I.A.", ""])
        lines.append(f"Source: {gaia_result.source}")
        lines.append(f"Data date: {gaia_result.data_date}")
        lines.append(f"Used G.A.I.A. data: {gaia_result.used_gaia}")
        lines.append(f"Commodity regime interpretation: {gaia_result.commodity_regime_interpretation}")
        dbc_score = next((score for score in scores if score.asset == "DBC"), None)
        gaia_caps = list(gaia_result.applied_caps)
        if dbc_score is not None and dbc_score.role_details.applied_caps:
            gaia_caps.extend(cap for cap in dbc_score.role_details.applied_caps if cap not in gaia_caps)
        if gaia_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in gaia_result.warnings)
        else:
            lines.extend(["", "Warnings:", "- none"])
        if gaia_caps:
            lines.extend(["", "Applied caps:"])
            lines.extend(f"- {cap}" for cap in gaia_caps)
        else:
            lines.extend(["", "Applied caps:", "- none"])
        if gaia_result.raw_metrics:
            lines.extend(["", "Raw metrics:"])
            lines.extend(f"- {name}: {value:+.6f}" for name, value in gaia_result.raw_metrics.items())
        lines.extend(["", "Proxy table:", "", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in gaia_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {gaia_result.reasons.get(name, 'neutral fallback')} |")
        lines.extend(["", "Reasons:"])
        lines.extend(f"- {name}: {reason}" for name, reason in gaia_result.reasons.items())

    if oracle_result is not None:
        for asset in ("VT", "BTC"):
            oracle_asset = oracle_result.assets.get(asset)
            lines.extend(["", f"## {asset} Opportunity generated by O.R.A.C.L.E.", ""])
            if oracle_asset is None:
                lines.append(f"Source: {oracle_result.source}")
                lines.append("Data date: unknown")
                lines.append("Used O.R.A.C.L.E. data: False")
                lines.append("opportunity_score: N/A")
                lines.append("oracle_signal: existing price_score fallback")
                lines.append("warnings:")
                relevant_warnings = oracle_result.warnings or [f"warning: O.R.A.C.L.E. data missing for {asset}; existing price_score fallback used."]
                lines.extend(f"- {warning}" for warning in relevant_warnings)
                continue
            lines.append(f"Source: {oracle_asset.source}")
            lines.append(f"Data date: {oracle_asset.data_date}")
            lines.append(f"Used O.R.A.C.L.E. data: {oracle_asset.used_oracle}")
            lines.append(f"opportunity_score: {oracle_asset.opportunity_score:.2f}")
            lines.append(f"oracle_signal: {oracle_asset.oracle_signal}")
            lines.append(f"value_score: {oracle_asset.value_score:.2f}")
            lines.append(f"sentiment_score: {oracle_asset.sentiment_score:.2f}")
            lines.append(f"drawdown_momentum_score: {oracle_asset.drawdown_momentum_score:.2f}")
            lines.append(f"cycle_score: {oracle_asset.cycle_score:.2f}")
            lines.extend(["", "components:"])
            for group, components in oracle_asset.components.items():
                lines.append(f"- {group}: {dict(components)}")
            lines.extend(["", "reasons:"])
            for group, reasons in oracle_asset.reasons.items():
                lines.extend(f"- {group}: {reason}" for reason in reasons)
            if oracle_asset.warnings:
                lines.extend(["", "warnings:"])
                lines.extend(f"- {warning}" for warning in oracle_asset.warnings)
            elif oracle_result.warnings:
                lines.extend(["", "warnings:"])
                lines.extend(f"- {warning}" for warning in oracle_result.warnings)
            else:
                lines.extend(["", "warnings:", "- none"])

    if arcadia_result is not None:
        lines.extend(["", "## XLRE Role inputs generated by A.R.C.A.D.I.A.", ""])
        lines.append(f"Source: {arcadia_result.source}")
        lines.append(f"Data date: {arcadia_result.data_date}")
        lines.append(f"Used A.R.C.A.D.I.A. data: {arcadia_result.used_arcadia}")
        lines.append(f"Real-estate regime interpretation: {arcadia_result.real_estate_regime_interpretation}")
        xlre_score = next((score for score in scores if score.asset == "XLRE"), None)
        arcadia_caps = list(arcadia_result.applied_caps)
        if xlre_score is not None and xlre_score.role_details.applied_caps:
            arcadia_caps.extend(cap for cap in xlre_score.role_details.applied_caps if cap not in arcadia_caps)
        if arcadia_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in arcadia_result.warnings)
        if arcadia_caps:
            lines.extend(["", "Applied caps:"])
            lines.extend(f"- {cap}" for cap in arcadia_caps)
        if arcadia_result.raw_metrics:
            lines.extend(["", "Raw metrics:"])
            lines.extend(f"- {name}: {value:+.6f}" for name, value in arcadia_result.raw_metrics.items())
        lines.extend(["", "Proxy table:", "", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in arcadia_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {arcadia_result.reasons.get(name, 'neutral fallback')} |")
        lines.extend(["", "Reasons:"])
        lines.extend(f"- {name}: {reason}" for name, reason in arcadia_result.reasons.items())

    lines.extend(["", "## Score Details", ""])
    for score in scores:
        lines.extend([
            f"### {score.asset}",
            "",
            f"Price components: {dict(score.price_details.components)}",
            f"Price reasons: {'; '.join(score.price_details.reasons)}",
            *( [f"G.A.I.A. commodity_regime_interpretation: {gaia_result.commodity_regime_interpretation}"] if score.asset == "DBC" and gaia_result is not None else [] ),
            f"Role components: {'N/A' if score.role_score is None else dict(score.role_details.components)}",
            f"Role raw_weighted_score: {'N/A' if score.role_score is None else score.role_details.raw_weighted_score}",
            f"Role penalty_adjusted_score: {'N/A' if score.role_score is None else score.role_details.penalty_adjusted_score}",
            f"Role core_score: {'N/A' if score.role_score is None else score.role_details.core_score}",
            f"Role support_score: {'N/A' if score.role_score is None else score.role_details.support_score}",
            f"Role penalty_score: {'N/A' if score.role_score is None else score.role_details.penalty_score}",
            f"Role applied_caps: {'N/A' if score.role_score is None else score.role_details.applied_caps}",
            f"Role interpretation: {'N/A' if score.role_score is None else score.role_details.role_interpretation}",
            f"Role reasons: {'; '.join(score.role_details.reasons)}",
            "",
        ])
    path.write_text(sanitize_output_text("\n".join(lines)), encoding="utf-8")
    return path
