"""CSV and Markdown report writers."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable, List, Optional

from .arcadia_adapter import ArcadiaResult
from .aura_adapter import AuraResult
from .inferno_adapter import InfernoResult
from .lode_adapter import LodeResult
from .config import ROLE_COMPONENT_GROUPS, ROLE_COMPONENT_WEIGHTS
from .scoring import AssetScore, ranking

OUTPUT_FIELDS = ["asset", "price_score", "role_score", "el_shaddai_score", "label", "main_reason", "data_date"]


def role_display(score: float | None) -> str:
    return "N/A" if score is None else f"{score:.2f}"


def write_csv(scores: Iterable[AssetScore], output_dir: Path) -> Path:
    path = output_dir / "el_shaddai_scores.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS, lineterminator="\n")
        writer.writeheader()
        for score in scores:
            writer.writerow({
                "asset": score.asset,
                "price_score": f"{score.price_score:.2f}",
                "role_score": role_display(score.role_score),
                "el_shaddai_score": f"{score.el_shaddai_score:.2f}",
                "label": score.label,
                "main_reason": score.main_reason,
                "data_date": score.data_date,
            })
    return path


def write_markdown(
    scores: List[AssetScore],
    output_dir: Path,
    source_summary: str,
    lode_result: Optional[LodeResult] = None,
    inferno_result: Optional[InfernoResult] = None,
    aura_result: Optional[AuraResult] = None,
    arcadia_result: Optional[ArcadiaResult] = None,
) -> Path:
    path = output_dir / "el_shaddai_report.md"
    lines = [
        "# El Shaddai Health Diagnostic Report",
        "",
        f"Data sources: {source_summary}",
        "",
        "## Asset Scores",
        "",
        "| asset | price_score | role_score | el_shaddai_score | label | main_reason | data_date |",
        "| --- | ---: | ---: | ---: | --- | --- | --- |",
    ]
    for score in scores:
        lines.append(
            f"| {score.asset} | {score.price_score:.2f} | {role_display(score.role_score)} | "
            f"{score.el_shaddai_score:.2f} | {score.label} | {score.main_reason} | {score.data_date} |"
        )

    lines.extend(["", "## Role Component Weights", "", "| asset | component | weight | group |", "| --- | --- | ---: | --- |"])
    for asset, weights in ROLE_COMPONENT_WEIGHTS.items():
        groups = ROLE_COMPONENT_GROUPS.get(asset, {})
        for component, weight in weights.items():
            lines.append(f"| {asset} | {component} | {weight:.2f} | {groups.get(component, 'core')} |")
    lines.extend(["", "## Genki-dama Candidate Ranking", "", "| rank | asset | score | label |", "| ---: | --- | ---: | --- |"])
    for index, score in enumerate(ranking(scores), start=1):
        lines.append(f"| {index} | {score.asset} | {score.el_shaddai_score:.2f} | {score.label} |")
    if lode_result is not None:
        lines.extend(["", "## TLT Role inputs generated by L.O.D.E.", ""])
        lines.append(f"Source: {lode_result.source}")
        lines.append(f"Data date: {lode_result.data_date}")
        lines.append(f"Used L.O.D.E. data: {lode_result.used_lode}")
        if lode_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in lode_result.warnings)
        lines.extend(["", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in lode_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {lode_result.reasons.get(name, 'neutral fallback')} |")

    if inferno_result is not None:
        lines.extend(["", "## TIP Role inputs generated by I.N.F.E.R.N.O.", ""])
        lines.append(f"Source: {inferno_result.source}")
        lines.append(f"Data date: {inferno_result.data_date}")
        lines.append(f"Used I.N.F.E.R.N.O. data: {inferno_result.used_inferno}")
        lines.append(f"Inflation regime interpretation: {inferno_result.inflation_regime_interpretation}")
        tip_score = next((score for score in scores if score.asset == "TIP"), None)
        inferno_caps = list(inferno_result.applied_caps)
        if tip_score is not None and tip_score.role_details.applied_caps:
            inferno_caps.extend(cap for cap in tip_score.role_details.applied_caps if cap not in inferno_caps)
        if inferno_caps:
            lines.extend(["", "Applied caps:"])
            lines.extend(f"- {cap}" for cap in inferno_caps)
        if inferno_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in inferno_result.warnings)
        lines.extend(["", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in inferno_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {inferno_result.reasons.get(name, 'neutral fallback')} |")

    if aura_result is not None:
        lines.extend(["", "## GLDM Role inputs generated by A.U.R.A.", ""])
        lines.append(f"Source: {aura_result.source}")
        lines.append(f"Enabled: {aura_result.used_aura}")
        lines.append(f"Data date: {aura_result.data_date}")
        lines.append(f"Dominant Anchor: {aura_result.dominant_anchor}")
        lines.append(f"Dominant Correlation: {aura_result.dominant_correlation:+.3f}")
        lines.append(f"GRI score: {aura_result.gri_score:+.3f}")
        lines.append(f"GRI interpretation: {aura_result.gri_interpretation}")
        if aura_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in aura_result.warnings)
        if aura_result.correlations:
            lines.extend(["", "Correlations:"])
            lines.extend(f"- {ticker}: {value:+.3f}" for ticker, value in aura_result.correlations.items())
        lines.extend(["", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in aura_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {aura_result.reasons.get(name, 'neutral fallback')} |")

    if arcadia_result is not None:
        lines.extend(["", "## XLRE Role inputs generated by A.R.C.A.D.I.A.", ""])
        lines.append(f"Source: {arcadia_result.source}")
        lines.append(f"Data date: {arcadia_result.data_date}")
        lines.append(f"Used A.R.C.A.D.I.A. data: {arcadia_result.used_arcadia}")
        lines.append(f"Real-estate regime interpretation: {arcadia_result.real_estate_regime_interpretation}")
        xlre_score = next((score for score in scores if score.asset == "XLRE"), None)
        arcadia_caps = list(arcadia_result.applied_caps)
        if xlre_score is not None and xlre_score.role_details.applied_caps:
            arcadia_caps.extend(cap for cap in xlre_score.role_details.applied_caps if cap not in arcadia_caps)
        if arcadia_result.warnings:
            lines.extend(["", "Warnings:"])
            lines.extend(f"- {warning}" for warning in arcadia_result.warnings)
        if arcadia_caps:
            lines.extend(["", "Applied caps:"])
            lines.extend(f"- {cap}" for cap in arcadia_caps)
        if arcadia_result.raw_metrics:
            lines.extend(["", "Raw metrics:"])
            lines.extend(f"- {name}: {value:+.6f}" for name, value in arcadia_result.raw_metrics.items())
        lines.extend(["", "Proxy table:", "", "| proxy | value | reason |", "| --- | ---: | --- |"])
        for name, value in arcadia_result.proxies.items():
            lines.append(f"| {name} | {value:+.3f} | {arcadia_result.reasons.get(name, 'neutral fallback')} |")
        lines.extend(["", "Reasons:"])
        lines.extend(f"- {name}: {reason}" for name, reason in arcadia_result.reasons.items())

    lines.extend(["", "## Score Details", ""])
    for score in scores:
        lines.extend([
            f"### {score.asset}",
            "",
            f"Price components: {dict(score.price_details.components)}",
            f"Price reasons: {'; '.join(score.price_details.reasons)}",
            f"Role components: {'N/A' if score.role_score is None else dict(score.role_details.components)}",
            f"Role raw_weighted_score: {'N/A' if score.role_score is None else score.role_details.raw_weighted_score}",
            f"Role penalty_adjusted_score: {'N/A' if score.role_score is None else score.role_details.penalty_adjusted_score}",
            f"Role core_score: {'N/A' if score.role_score is None else score.role_details.core_score}",
            f"Role support_score: {'N/A' if score.role_score is None else score.role_details.support_score}",
            f"Role penalty_score: {'N/A' if score.role_score is None else score.role_details.penalty_score}",
            f"Role applied_caps: {'N/A' if score.role_score is None else score.role_details.applied_caps}",
            f"Role interpretation: {'N/A' if score.role_score is None else score.role_details.role_interpretation}",
            f"Role reasons: {'; '.join(score.role_details.reasons)}",
            "",
        ])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
