"""HTML/SVG visualization for El Shaddai."""

from __future__ import annotations

from pathlib import Path
from typing import List

from .aura_adapter import AuraResult
from .config import PERMANENT_ASSETS
from .report import role_display
from .scoring import AssetScore, ranking

NEUTRAL_ROLE_WARNING = "Role proxy inputs are neutral placeholders. This dashboard is not yet an operational role audit."


def _html_escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _reason_short(score: AssetScore) -> str:
    return score.main_reason.split("; ", 1)[0]


def _label_class(score_value: float) -> str:
    if score_value >= 80:
        return "opportunity"
    if score_value >= 60:
        return "watch"
    if score_value >= 40:
        return "neutral"
    if score_value >= 20:
        return "weak"
    return "risk"


def _details_reason(score: AssetScore) -> str:
    short = _html_escape(_reason_short(score))
    full = _html_escape(score.main_reason)
    return f"<details><summary>{short}</summary>{full}</details>"


def _role_scores_are_neutral(scores: List[AssetScore]) -> bool:
    role_scores = [score.role_score for score in scores if score.asset not in PERMANENT_ASSETS and score.role_score is not None]
    return bool(role_scores) and all(round(float(role_score), 2) == 50.0 for role_score in role_scores)


def _table_row(score: AssetScore, include_role: bool = True) -> str:
    css_class = _label_class(score.el_shaddai_score)
    role_cell = f"<td>{role_display(score.role_score)}</td>" if include_role else ""
    return (
        f'<tr class="{css_class}"><td>{score.asset}</td><td>{score.price_score:.2f}</td>{role_cell}'
        f"<td>{score.el_shaddai_score:.2f}</td><td><span class=\"badge {css_class}\">{_html_escape(score.label)}</span></td>"
        f"<td>{_details_reason(score)}</td><td>{score.data_date}</td></tr>"
    )


def write_html(scores: List[AssetScore], output_dir: Path, aura_result: AuraResult | None = None) -> Path:
    path = output_dir / "el_shaddai_dashboard.html"
    ranked_scores = ranking(scores)
    permanent_scores = [score for score in scores if score.asset in PERMANENT_ASSETS]
    role_scores = [score for score in scores if score.asset not in PERMANENT_ASSETS]
    neutral_role_warning = _role_scores_are_neutral(scores)
    data_date = scores[0].data_date if scores else "unknown"
    top_candidate = ranked_scores[0] if ranked_scores else None
    vt = next((score for score in scores if score.asset == "VT"), None)
    btc = next((score for score in scores if score.asset == "BTC"), None)
    strongest_role = max(role_scores, key=lambda score: score.el_shaddai_score, default=None)
    weak_or_risk = [score for score in scores if score.el_shaddai_score < 40]

    warning_html = f'<div class="warning">{NEUTRAL_ROLE_WARNING}</div>' if neutral_role_warning else ""
    aura_note = ""
    if aura_result is not None:
        aura_note = (
            '<section><h2>GLDM Role generated by A.U.R.A.</h2>'
            f'<p>Enabled: {aura_result.used_aura}</p>'
            f'<p>Dominant Anchor: {_html_escape(aura_result.dominant_anchor)} '
            f'({aura_result.dominant_correlation:+.3f})</p>'
            f'<p>GRI: {aura_result.gri_score:+.3f} - {_html_escape(aura_result.gri_interpretation)}</p>'
            '</section>'
        )
    summary_rows = [
        ("data_date", data_date),
        ("Top Genki-dama candidate", f"{top_candidate.asset} ({top_candidate.el_shaddai_score:.2f}, {top_candidate.label})" if top_candidate else "N/A"),
        ("VT Value Opportunity Score", f"{vt.el_shaddai_score:.2f} ({vt.label})" if vt else "N/A"),
        ("BTC Value Opportunity Score", f"{btc.el_shaddai_score:.2f} ({btc.label})" if btc else "N/A"),
        ("Strongest Role-audited asset", f"{strongest_role.asset} ({strongest_role.el_shaddai_score:.2f}, {strongest_role.label})" if strongest_role else "N/A"),
        ("Assets in Weak or Risk", ", ".join(score.asset for score in weak_or_risk) if weak_or_risk else "None"),
        ("Role proxy note", NEUTRAL_ROLE_WARNING if neutral_role_warning else "Role proxy inputs include non-neutral values."),
    ]
    summary = "\n".join(f"<tr><th>{_html_escape(name)}</th><td>{_html_escape(value)}</td></tr>" for name, value in summary_rows)

    permanent_rows = "\n".join(
        f'<tr class="{_label_class(score.el_shaddai_score)}"><td>{score.asset}</td><td>{score.el_shaddai_score:.2f}</td>'
        f'<td><span class="badge {_label_class(score.el_shaddai_score)}">{_html_escape(score.label)}</span></td><td>{_html_escape(_reason_short(score))}</td></tr>'
        for score in permanent_scores
    )
    all_rows = "\n".join(_table_row(score) for score in scores)

    points = []
    for score in role_scores:
        if score.role_score is None:
            continue
        x = 60 + score.price_score * 4.8
        y = 540 - score.role_score * 4.8
        points.append(
            f'<circle class="point {_label_class(score.el_shaddai_score)}" cx="{x:.1f}" cy="{y:.1f}" r="8">'
            f"<title>{score.asset}</title></circle><text x=\"{x+10:.1f}\" y=\"{y+4:.1f}\">{score.asset}</text>"
        )
    ranking_rows = "\n".join(
        f'<tr class="{_label_class(score.el_shaddai_score)}"><td>{index}</td><td>{score.asset}</td><td>{score.el_shaddai_score:.2f}</td>'
        f'<td><span class="badge {_label_class(score.el_shaddai_score)}">{_html_escape(score.label)}</span></td><td>{_html_escape(_reason_short(score))}</td></tr>'
        for index, score in enumerate(ranked_scores, start=1)
    )
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>El Shaddai Dashboard</title>
<style>
body {{ font-family: system-ui, sans-serif; margin: 2rem; color: #172033; background: #f7f9fc; }}
section {{ background: white; border: 1px solid #d5dbe7; border-radius: 10px; margin: 1.2rem 0; padding: 1rem; box-shadow: 0 1px 3px rgba(20, 31, 50, 0.06); }}
table {{ border-collapse: collapse; width: 100%; font-size: 0.92rem; background: white; }}
th, td {{ border: 1px solid #d5dbe7; padding: 0.45rem; vertical-align: top; }}
th {{ background: #eef3fb; text-align: left; }}
tr.opportunity {{ background: #eaf7ee; }} tr.watch {{ background: #fff8df; }} tr.neutral {{ background: #f4f6fa; }} tr.weak {{ background: #fff0df; }} tr.risk {{ background: #ffe9e9; }}
.badge {{ border-radius: 999px; color: #172033; display: inline-block; font-weight: 700; padding: 0.15rem 0.55rem; }}
.badge.opportunity {{ background: #7bd99a; }} .badge.watch {{ background: #ffd866; }} .badge.neutral {{ background: #d9e0ec; }} .badge.weak {{ background: #ffb45f; }} .badge.risk {{ background: #ff8585; }}
.warning {{ background: #fff0df; border: 1px solid #f2a65a; border-radius: 8px; font-weight: 700; margin: 1rem 0; padding: 0.8rem; }}
svg {{ border: 1px solid #d5dbe7; background: #fbfcff; max-width: 100%; }}
.point {{ fill: #3366cc; opacity: 0.78; }} .point.opportunity {{ fill: #16883a; }} .point.watch {{ fill: #c79500; }} .point.neutral {{ fill: #657386; }} .point.weak {{ fill: #c96900; }} .point.risk {{ fill: #c72828; }}
.axis {{ stroke: #637083; stroke-width: 1; }} .grid {{ stroke: #e1e6ef; stroke-width: 1; }} .quadrant {{ fill: #637083; font-size: 13px; font-weight: 700; }}
summary {{ cursor: pointer; font-weight: 600; }}
</style>
</head>
<body>
<h1>El Shaddai Health Diagnostic Dashboard</h1>
{warning_html}
{aura_note}
<section><h2>Executive Summary</h2><table><tbody>{summary}</tbody></table></section>
<section><h2>Permanent Holdings / Value Opportunity Only</h2>
<p>VT and BTC are permanent holding assets. Role diagnosis is intentionally not applied; only spot-buy opportunity is evaluated.</p>
<table><thead><tr><th>asset</th><th>value_opportunity_score</th><th>label</th><th>reason_short</th></tr></thead><tbody>{permanent_rows}</tbody></table></section>
<section><h2>Genki-dama Candidate Ranking</h2>
<table><thead><tr><th>rank</th><th>asset</th><th>score</th><th>label</th><th>reason_short</th></tr></thead><tbody>{ranking_rows}</tbody></table></section>
<section><h2>All Assets</h2>
<table><thead><tr><th>asset</th><th>price_score</th><th>role_score</th><th>el_shaddai_score</th><th>label</th><th>main_reason</th><th>data_date</th></tr></thead><tbody>{all_rows}</tbody></table></section>
<section><h2>Price × Role Matrix</h2>
<p>Price Score is higher when an asset is cheaper, more pessimistic, and more attractive for incremental capital.</p>
<svg viewBox="0 0 600 600" role="img" aria-label="Price by role scatter plot">
<line class="axis" x1="60" y1="540" x2="540" y2="540"/><line class="axis" x1="60" y1="540" x2="60" y2="60"/>
<line class="grid" x1="300" y1="540" x2="300" y2="60"/><line class="grid" x1="60" y1="300" x2="540" y2="300"/>
<text x="250" y="585">Price Score</text><text x="5" y="45">Role Score</text>
<text x="52" y="558">0</text><text x="528" y="558">100</text><text x="30" y="64">100</text>
<text class="quadrant" x="315" y="85">High Price Opportunity / High Role</text>
<text class="quadrant" x="315" y="525">High Price Opportunity / Low Role</text>
<text class="quadrant" x="75" y="85">Low Price Opportunity / High Role</text>
<text class="quadrant" x="75" y="525">Low Price Opportunity / Low Role</text>
{''.join(points)}
</svg></section>
</body></html>"""
    path.write_text(html, encoding="utf-8")
    return path
